// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	loadbalancer "github.com/krossroad/roundrobinecho/internal/loadbalancer"
	mock "github.com/stretchr/testify/mock"
)

// LoadBalancer is an autogenerated mock type for the LoadBalancer type
type LoadBalancer struct {
	mock.Mock
}

// Backends provides a mock function with given fields:
func (_m *LoadBalancer) Backends() []loadbalancer.Backend {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Backends")
	}

	var r0 []loadbalancer.Backend
	if rf, ok := ret.Get(0).(func() []loadbalancer.Backend); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]loadbalancer.Backend)
		}
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *LoadBalancer) Next() (loadbalancer.Backend, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 loadbalancer.Backend
	var r1 error
	if rf, ok := ret.Get(0).(func() (loadbalancer.Backend, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() loadbalancer.Backend); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(loadbalancer.Backend)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLoadBalancer creates a new instance of LoadBalancer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoadBalancer(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoadBalancer {
	mock := &LoadBalancer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
